create table attribute
(
    enabled    boolean                                                          not null,
    id         bigint generated by default as identity,
    input_type enum('BOOLEAN', 'DATE', 'DATETIME', 'DECIMAL', 'NUMBER', 'TEXT') not null,
    primary key (id)
)
;
create table attribute_descriptions
(
    attribute_id              bigint       not null,
    descriptions_attribute_id bigint       not null,
    descriptions_locale       varchar(255) not null,
    primary key (attribute_id, descriptions_attribute_id, descriptions_locale),
    unique (descriptions_attribute_id, descriptions_locale)
)
;
create table attribute_description
(
    attribute_id bigint       not null,
    locale       varchar(255) not null,
    name         varchar(255) not null,
    primary key (attribute_id, locale)
)
;
create table brand
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
)
;
create table category
(
    enabled    boolean not null,
    sort_order integer not null,
    created_at timestamp(6) with time zone,
    id         bigint generated by default as identity,
    parent_id  bigint,
    updated_at timestamp(6) with time zone,
    image_id   uuid,
    primary key (id)
)
;
create table category_attributes
(
    attributes_attribute_id bigint not null,
    attributes_category_id  bigint not null,
    category_id             bigint not null,
    primary key (attributes_attribute_id, attributes_category_id, category_id),
    unique (attributes_attribute_id, attributes_category_id)
)
;
create table category_descriptions
(
    category_id              bigint       not null,
    descriptions_category_id bigint       not null,
    descriptions_locale      varchar(255) not null,
    primary key (category_id, descriptions_category_id, descriptions_locale),
    unique (descriptions_category_id, descriptions_locale)
)
;
create table category_attribute
(
    mandatory      boolean not null,
    sort_order     integer not null,
    use_in_filters boolean not null,
    attribute_id   bigint  not null,
    category_id    bigint  not null,
    primary key (attribute_id, category_id)
)
;
create table category_description
(
    category_id      bigint       not null,
    locale           varchar(255) not null,
    meta_description varchar(255),
    meta_title       varchar(255),
    title            varchar(255),
    description      clob,
    primary key (category_id, locale)
)
;
create table image
(
    id   uuid not null,
    name varchar(255),
    src  varchar(255),
    primary key (id)
)
;
create table product
(
    currency     varchar(3),
    enabled      boolean not null,
    price        numeric(15, 3),
    weight       numeric(15, 8),
    brand_id     bigint,
    category_id  bigint  not null,
    created_at   timestamp(6) with time zone,
    id           bigint generated by default as identity,
    updated_at   timestamp(6) with time zone,
    ean          varchar(14),
    sku          varchar(64) unique,
    weight_class enum('GRAM', 'KILOGRAM'),
    primary key (id)
)
;
create table product_additional_categories
(
    additional_categories_category_id bigint not null,
    additional_categories_product_id  bigint not null,
    product_id                        bigint not null,
    primary key (additional_categories_category_id, additional_categories_product_id, product_id),
    unique (additional_categories_category_id, additional_categories_product_id)
)
;
create table product_descriptions
(
    descriptions_product_id bigint       not null,
    product_id              bigint       not null,
    descriptions_locale     varchar(255) not null,
    primary key (descriptions_product_id, product_id, descriptions_locale),
    unique (descriptions_locale, descriptions_product_id)
)
;
create table product_image
(
    product_id bigint not null,
    image_id   uuid   not null,
    primary key (product_id, image_id)
)
;
create table product_tags
(
    product_id bigint not null,
    tags       varchar(255)
)
;
create table product_additional_category
(
    category_id bigint not null,
    product_id  bigint not null,
    primary key (category_id, product_id)
)
;
create table product_additional_image
(
    sort_order integer not null,
    product_id bigint  not null,
    image_id   uuid    not null,
    primary key (product_id, image_id)
)
;
create table product_attribute
(
    attribute_id    bigint,
    product_id      bigint       not null,
    attribute_value varchar(255) not null,
    primary key (product_id)
)
;
create table product_description
(
    product_id       bigint       not null,
    locale           varchar(255) not null,
    meta_description varchar(255),
    meta_title       varchar(255),
    title            varchar(255),
    description      clob,
    primary key (product_id, locale)
)
;
alter table if exists attribute_descriptions
    add constraint FKip55w02e48r9s5d6od1o44pi0 foreign key (descriptions_attribute_id, descriptions_locale) references attribute_description
;
alter table if exists attribute_descriptions
    add constraint FKo1evy1fy198x6dklx5vpkc3lc foreign key (attribute_id) references attribute
;
alter table if exists attribute_description
    add constraint FKaruy9s6g1jfxc2ryq8wnriok8 foreign key (attribute_id) references attribute
;
alter table if exists category
    add constraint FKllo73u8jwer0wg1qs3blpxxyw foreign key (image_id) references image
;
alter table if exists category
    add constraint FK2y94svpmqttx80mshyny85wqr foreign key (parent_id) references category
;
alter table if exists category_attributes
    add constraint FKggq19ds5pcaj15qlpfaoeor7b foreign key (attributes_attribute_id, attributes_category_id) references category_attribute
;
alter table if exists category_attributes
    add constraint FKqyf0cmv6sc4k6qets4ulike7f foreign key (category_id) references category
;
alter table if exists category_descriptions
    add constraint FK5gddbql27aqmn62a27qg41kfg foreign key (descriptions_category_id, descriptions_locale) references category_description
;
alter table if exists category_descriptions
    add constraint FKid8nh7sd88jttl09m50twxly8 foreign key (category_id) references category
;
alter table if exists category_attribute
    add constraint FKe0pcstwj0x32r32yy4e8impwv foreign key (category_id) references category
;
alter table if exists category_attribute
    add constraint FKi8qw5dueeesbkbslbpfopnrkl foreign key (attribute_id) references attribute
;
alter table if exists category_description
    add constraint FKcf1yvvfw0o7fvhxpryuetekcb foreign key (category_id) references category
;
alter table if exists product
    add constraint FKs6cydsualtsrprvlf2bb3lcam foreign key (brand_id) references brand
;
alter table if exists product
    add constraint FK1mtsbur82frn64de7balymq9s foreign key (category_id) references category
;
alter table if exists product_additional_categories
    add constraint FK6861et7b1av5jfppqrtm50288 foreign key (additional_categories_category_id, additional_categories_product_id) references product_additional_category
;
alter table if exists product_additional_categories
    add constraint FKjy1n3k69mipjp1qhkyigs5l2y foreign key (product_id) references product
;
alter table if exists product_descriptions
    add constraint FKnv4b3hsy0n8xw9o8lur6dohf1 foreign key (descriptions_product_id, descriptions_locale) references product_description
;
alter table if exists product_descriptions
    add constraint FK58navhy0wx495ph6pg1hnjdwr foreign key (product_id) references product
;
alter table if exists product_image
    add constraint FKbhddxsl8axd5io2wgkcoealn5 foreign key (image_id) references image
;
alter table if exists product_image
    add constraint FK6oo0cvcdtb6qmwsga468uuukk foreign key (product_id) references product
;
alter table if exists product_tags
    add constraint FK8gmf959fnpxtkagtk56mbaj0e foreign key (product_id) references product
;
alter table if exists product_additional_category
    add constraint FKjdf6acoag28qjxrbspns43yk foreign key (category_id) references category
;
alter table if exists product_additional_category
    add constraint FKk47bc3ahbo9de2106scy8rtfa foreign key (product_id) references product
;
alter table if exists product_additional_image
    add constraint FK8jleyu2xl3am44e7bce8v60gm foreign key (product_id) references product
;
alter table if exists product_additional_image
    add constraint FKmomchcmttriibrsrpfq1c7fgm foreign key (image_id) references image
;
alter table if exists product_attribute
    add constraint FKefc9famxhv98xs6686269a79 foreign key (attribute_id) references attribute
;
alter table if exists product_attribute
    add constraint FKlefs59y5kmsbu017n1wp10gf2 foreign key (product_id) references product
;
alter table if exists product_description
    add constraint FK9iiotbwtk1n1b6dgga729sg9q foreign key (product_id) references product
